"""
NOVA — Report Model
Mirrors report metadata generated by app/services/reports/report_generator.py.
"""

import uuid
from typing import Optional

from sqlalchemy import String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.db.mixins import TimestampMixin, UUIDPrimaryKeyMixin

REPORT_TYPE_MAX_LENGTH = 32
REPORT_STATUS_MAX_LENGTH = 16


class Report(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "reports"
    __table_args__ = (
        UniqueConstraint("scan_job_id", "report_type", name="uq_reports_scan_job_id_report_type"),
    )

    scan_job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), nullable=False, index=True
    )
    report_type: Mapped[str] = mapped_column(String(REPORT_TYPE_MAX_LENGTH), nullable=False)
    status: Mapped[str] = mapped_column(String(REPORT_STATUS_MAX_LENGTH), nullable=False, default="pending")

    file_path: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)
    storage_backend: Mapped[str] = mapped_column(String(16), nullable=False, default="local")
    storage_key: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)

    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
