{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kavach.fullname" . }}
  labels:
    {{- include "kavach.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.apiPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kavach.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
          {{- if .Values.frontend.enabled }}
          - path: {{ .Values.ingress.frontendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "kavach.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          {{- end }}
{{- end }}
