{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kavach.fullname" . }}-postgres
  labels:
    {{- include "kavach.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kavach.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "kavach.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kavach.fullname" . }}-redis
  labels:
    {{- include "kavach.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kavach.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "kavach.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
